all:
  hosts:
    localhost:
  children:
    dev:
      hosts:
        localhost:
    webservers:
      hosts:
        palladio:
    dbservers:
      hosts:
        palladio:
    dns:
      hosts:
        palladio:
        test01:
    git: 
      hosts:
        palladio:
